version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      all:
        patterns:
          - '*'
  - package-ecosystem: 'pip'
    directory: '/requirements/'
    schedule:
      interval: 'monthly'
    groups:
      all:
        patterns:
          - '*'
