name: Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tests:
    name: ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ['3.12', '3.11', '3.10', '3.9', '3.8']
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true
          cache: pip
          cache-dependency-path: requirements/tests.txt
      - run: pip install tox
      - run: tox run -e py${{ matrix.python }}
  min:
    name: Minimum Versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: '3.8'
          cache: pip
          cache-dependency-path: requirements/tests.txt
      - run: pip install tox
      - run: tox run -e py-min
